services:
  source_postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./elt_script/init_source.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  destination_postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  elt_script:
    build: ./elt_script
    depends_on:
      source_postgres:
        condition: service_healthy
      destination_postgres:
        condition: service_healthy

  airflow_postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow

  airflow:
    image: apache/airflow:2.6.3
    depends_on:
      - airflow_postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=mysecretkey
      - AIRFLOW__WEBSERVER__WORKERS=1
      - AIRFLOW__WEBSERVER__WORKER_REFRESH_BATCH_SIZE=1
      - AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT=300
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - _AIRFLOW_WWW_USER_FIRSTNAME=Lokesh
      - _AIRFLOW_WWW_USER_LASTNAME=Reddy
      - _AIRFLOW_WWW_USER_EMAIL=lokesh@gmail.com
      - _AIRFLOW_WWW_USER_ROLE=Admin
      - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
      - AIRFLOW__SMTP__SMTP_PORT=587
      - AIRFLOW__SMTP__SMTP_STARTTLS=True
      - AIRFLOW__SMTP__SMTP_SSL=False
      - AIRFLOW__SMTP__SMTP_USER=lokeshreddynarapureddy3@gmail.com
      - AIRFLOW__SMTP__SMTP_PASSWORD=your_app_password_here
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=lokeshreddynarapureddy3@gmail.com
      - _PIP_ADDITIONAL_REQUIREMENTS=dbt-core==1.5.11 dbt-postgres==1.5.11
    volumes:
      - ./dags:/opt/airflow/dags
      - ./elt_script:/app
      - ./dbt:/dbt
    ports:
      - "8080:8080"
    command: bash -c "chmod -R 777 /dbt && airflow db init && airflow users create --username admin --password admin --firstname Lokesh --lastname Reddy --role Admin --email lokesh@gmail.com ; airflow webserver & airflow scheduler"